import {APP_VERSION,SCHEMA_VERSION,defaultState,migrateState,deepClone,uid,DAYS,classById,teacherById,facilityById,lessonById,cycleSessionsForLesson,validateState,normalizeResources,applySchoolTypeDefaults,standardUnitMinutesForSchool,implementationPeriodsForStandardUnits,implementationExactPeriods} from './model.js';
import {loadState,saveState,downloadText,readFile} from './storage.js';
import {calendarStats,weeklyTargetForGrade,dailyPattern,gradePatterns,monthMatrix,typeLabel,isoDate} from './calendar.js';
import {solveSchedule,scheduleMetrics,movePlacement,placeLesson,absenceProposals,buildSolverModel} from './solver-client.js';
import {saveToDrive,loadFromDrive} from './drive.js';
import {reportByType} from './reports.js';

const NAV=[
  ['basic','01','基本情報'],['goals','02','教育目標・重点'],['calendar','03','年間カレンダー'],['days','04','授業日数・週時数'],
  ['hours','05','授業時数'],['integrated','06','総合・特別活動'],['periods','07','校時表'],['resources','08','時間割データ'],
  ['timetable','09','時間割編成'],['operations','10','臨時変更・欠勤'],['checks','11','最終チェック'],['reports','12','帳票・保存']
];
let state=null,saveTimer=null,busy=false,metricsCache=null,absenceCache=null,deferredPrompt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const attr=s=>esc(s).replace(/`/g,'&#96;');
function toast(msg,type=''){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toasts').appendChild(el);setTimeout(()=>el.remove(),3300)}
function fmtTime(iso){if(!iso)return '未同期';try{return new Date(iso).toLocaleString('ja-JP')}catch{return iso}}
function n(v,d=0){const x=Number(v);return Number.isFinite(x)?x:d}
function setByPath(obj,path,val){const parts=path.split('.');let cur=obj;for(let i=0;i<parts.length-1;i++){const k=/^\d+$/.test(parts[i])?Number(parts[i]):parts[i];cur=cur[k]}const k=/^\d+$/.test(parts.at(-1))?Number(parts.at(-1)):parts.at(-1);cur[k]=val}
function getByPath(obj,path){return path.split('.').reduce((a,k)=>a?.[/^\d+$/.test(k)?Number(k):k],obj)}
function input(path,value,type='text',extra=''){return `<input type="${type}" value="${attr(value??'')}" data-bind="${path}" ${extra}>`}
function select(path,value,options,extra=''){return `<select data-bind="${path}" ${extra}>${options.map(([v,l])=>`<option value="${attr(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select>`}
function checkbox(path,val,label,extra=''){return `<label class="inline"><input type="checkbox" data-bind="${path}" ${val?'checked':''} ${extra}> <span>${esc(label)}</span></label>`}
function pageHead(title,desc,meta=''){return `<div class="page-head"><div><h2>${esc(title)}</h2><p>${desc}</p></div><div class="page-meta">${meta}</div></div>`}
function field(label,control,span='span4',help=''){return `<div class="field ${span}"><label>${esc(label)}</label>${control}${help?`<div class="help">${help}</div>`:''}</div>`}
function card(title,body,sub=''){return `<div class="card"><h3>${esc(title)}</h3>${sub?`<div class="sub">${sub}</div>`:''}${body}</div>`}
function metric(label,value,unit='',note=''){return `<div class="card metric"><div class="label">${esc(label)}</div><div class="value">${esc(value)}<span class="unit">${esc(unit)}</span></div>${note?`<div class="note">${note}</div>`:''}</div>`}
function navState(page){if(page==='timetable'&&metricsCache){if(metricsCache.hard?.length)return 'err';if(metricsCache.unplaced)return 'warn';return 'ok'}if(page==='checks'){const issues=validateState(state,calendarStats(state));if(issues.some(x=>x.level==='ERROR'))return 'err';if(issues.some(x=>x.level==='WARNING'))return 'warn';return 'ok'}return 'ok'}

async function init(){
  const raw=await loadState().catch(()=>null);state=migrateState(raw||defaultState());normalizeResources(state);state.timetable.cycleWeeks=n(state.timetable.cycleWeeks||state.instruction.cycleWeeks,2);state.instruction.cycleWeeks=state.timetable.cycleWeeks;
  bindGlobal();render();refreshMetrics();
  if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(e=>console.warn(e))}
}
function bindGlobal(){
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});
  $('#installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true});
  window.addEventListener('online',updateTop);window.addEventListener('offline',updateTop);
  document.body.addEventListener('click',handleClick);document.body.addEventListener('input',handleBind);document.body.addEventListener('change',handleChange);
  document.body.addEventListener('dragstart',handleDragStart);document.body.addEventListener('dragover',e=>{if(e.target.closest('[data-drop]')){e.preventDefault();e.target.closest('[data-drop]').classList.add('drop-target')}});document.body.addEventListener('dragleave',e=>e.target.closest('[data-drop]')?.classList.remove('drop-target'));document.body.addEventListener('drop',handleDrop);
}
function handleBind(e){const path=e.target.dataset.bind;if(!path)return;let v=e.target.type==='checkbox'?e.target.checked:e.target.value;if(e.target.dataset.number!==undefined)v=n(v);if(e.target.dataset.boolean!==undefined)v=String(v)==='true';setByPath(state,path,v);if(path==='goals.featureTagsText')state.goals.featureTags=String(v).split(/[、,]/).map(x=>x.trim()).filter(Boolean);const sm=path.match(/^resources\.teachers\.(\d+)\.subjectsText$/);if(sm)state.resources.teachers[Number(sm[1])].subjects=String(v).split(/[、,]/).map(x=>x.trim()).filter(Boolean);if(path==='timetable.cycleWeeks'){state.instruction.cycleWeeks=n(v,1);state.timetable.view.week=Math.min(state.timetable.view.week,n(v,1)-1)}state.updatedAt=new Date().toISOString();scheduleSave();if(e.target.dataset.live==='top')updateTop()}
function scheduleSave(){clearTimeout(saveTimer);$('#saveChip').textContent='保存中…';saveTimer=setTimeout(async()=>{try{await saveState(state);$('#saveChip').textContent='端末に保存済み'}catch(e){$('#saveChip').textContent='保存失敗';toast(e.message,'err')}},450)}
function render(){renderNav();updateTop();const c=$('#content');const fn={basic:renderBasic,goals:renderGoals,calendar:renderCalendar,days:renderDays,hours:renderHours,integrated:renderIntegrated,periods:renderPeriods,resources:renderResources,timetable:renderTimetable,operations:renderOperations,checks:renderChecks,reports:renderReports}[state.ui.page]||renderBasic;c.innerHTML=fn();afterRender()}
function renderNav(){$('#nav').innerHTML=`<div class="nav-title">学校で作成</div>`+NAV.map(([id,num,label])=>`<div class="nav-item ${state.ui.page===id?'active':''}" data-nav="${id}"><span class="num">${num}</span><span class="label">${label}</span><span class="state ${navState(id)}">●</span></div>`).join('')}
function updateTop(){$('#topSchool').textContent=state.school.name||'学校未設定';$('#topMeta').textContent=`${state.school.fiscalYear}年度｜School v${APP_VERSION}`;const ch=$('#onlineChip');ch.className=`chip ${navigator.onLine?'ok':'warn'}`;ch.textContent=navigator.onLine?'● オンライン / オフライン対応':'● オフラインで作業中'}
function afterRender(){if(state.ui.page==='reports')renderReportPreview();}
async function refreshMetrics(){try{metricsCache=await scheduleMetrics(state);if(state.ui.page==='timetable'||state.ui.page==='checks')render();else renderNav()}catch(e){console.warn(e)}}
function pushUndo(){state.timetable.undo=state.timetable.undo||[];state.timetable.undo.push(deepClone(state.timetable.placements));if(state.timetable.undo.length>30)state.timetable.undo.shift();state.timetable.redo=[]}
function applyPlacements(ps){pushUndo();state.timetable.placements=ps;state.updatedAt=new Date().toISOString();scheduleSave();refreshMetrics();render()}

function renderBasic(){
  const stdMin=standardUnitMinutesForSchool(state.school.type);const actualMin=Number(state.school.lessonMinutes||stdMin);const sampleStd=state.school.type==='junior_high'?1015:(state.hourPlans[0]?.annualTarget||0);const sampleImpl=implementationPeriodsForStandardUnits(state,sampleStd);const exactImpl=implementationExactPeriods(state,sampleStd);
  return pageHead('01 基本情報','学校・年度・校種など、教育課程編成の基礎情報を設定します。',`<span class="chip info">スキーマ v${SCHEMA_VERSION}</span>`)+
  `<div class="grid cols2">${card('学校情報',`<div class="form-grid">
    ${field('学校名',input('school.name',state.school.name,'text','data-live="top"'),'span8')}
    ${field('学校コード',input('school.code',state.school.code),'span4')}
    ${field('校種',select('school.type',state.school.type,[['elementary','小学校'],['junior_high','中学校']],'data-rerender'),'span4','校種を変更すると、教科・標準時数・時間割基礎データを校種別に切り替えます。')}
    ${field('校長名',input('school.principal',state.school.principal),'span4')}
    ${field('年度',input('school.fiscalYear',state.school.fiscalYear,'number','data-number data-rerender'),'span4','年度変更後は年間カレンダーの期間も確認してください。')}
    ${field('実施1コマ（分）',input('school.lessonMinutes',state.school.lessonMinutes,'number','data-number data-rerender'),'span3',`標準1単位時間：${stdMin}分`)}
    ${field('学期制',select('school.termSystem',state.school.termSystem,[[2,'2学期制'],[3,'3学期制']],'data-number'),'span3')}
    ${field('備考',`<textarea data-bind="school.notes">${esc(state.school.notes)}</textarea>`,'span12')}
  </div><div class="notice info" style="margin-top:10px"><strong>${state.school.type==='elementary'?'小学校':'中学校'}：</strong>標準1単位時間は${stdMin}分です。実施1コマを${actualMin}分にすると、標準時数は授業分数で自動換算します。${actualMin!==stdMin?` 例：標準${sampleStd}単位 → ${sampleStd}×${stdMin}÷${actualMin}=${exactImpl.toFixed(2)} → <strong>${sampleImpl}コマ以上</strong>必要。`:''}</div>`) }
  ${card('この学校版の保存方式',`<div class="notice ok">入力内容はChromebook/PCのIndexedDBへ自動保存します。Google Drive同期は任意で、ネットワークがない状態でも教育課程・時間割の編集を続けられます。</div>
  <div class="kpi-line"><span>最終更新</span><strong>${fmtTime(state.updatedAt)}</strong></div>
  <div class="kpi-line"><span>Drive最終同期</span><strong>${fmtTime(state.drive.lastSyncAt)}</strong></div>
  <div class="inline" style="margin-top:10px"><button class="btn" data-action="openDrive">Drive設定</button><button class="btn" data-action="exportJson">JSONバックアップ</button><button class="btn" data-action="importJson">JSON復元</button></div>`)}
  </div>`;
}

function renderGoals(){
  return pageHead('02 教育目標・指導の重点','学校教育目標と、今年度の重点・特色を学校自身で記述します。')+
  `${card('学校教育目標',`<div class="field"><textarea data-bind="goals.educationGoal" placeholder="学校教育目標を入力">${esc(state.goals.educationGoal)}</textarea></div>`) }
  <div style="height:12px"></div>
  ${card('指導の重点',`<div class="grid cols2">${state.goals.focusItems.map((x,i)=>`<div class="card flat"><div class="inline"><strong style="color:var(--navy)">${esc(x.label)}</strong><button class="btn small danger right" data-action="removeFocus" data-index="${i}">削除</button></div><div class="field" style="margin-top:7px"><input data-bind="goals.focusItems.${i}.label" value="${attr(x.label)}" placeholder="項目名"><textarea data-bind="goals.focusItems.${i}.text" placeholder="重点内容">${esc(x.text||'')}</textarea></div></div>`).join('')}</div><div style="margin-top:10px"><button class="btn" data-action="addFocus">＋ 項目を追加</button></div>`)}
  <div style="height:12px"></div>
  ${card('今年度の特色',`<div class="form-grid">${field('特色の要約',`<textarea data-bind="goals.featureSummary" placeholder="今年度、特に力を入れる教育課程上の工夫を記述">${esc(state.goals.featureSummary||'')}</textarea>`,'span8')}${field('特色タグ',input('goals.featureTagsText',(state.goals.featureTags||[]).join('、')),'span4','読点「、」区切り。例：探究、地域連携、情報教育')}</div>`,'将来、市教委版へ提出する場合は学校特色ダッシュボードに利用できます。')}`;
}

function renderCalendar(){
  const stats=calendarStats(state),fy=Number(state.school.fiscalYear),months=[];for(let i=0;i<12;i++){const m=(3+i)%12,y=fy+(m<3?1:0);months.push(renderMiniMonth(y,m,stats))}
  return pageHead('03 年間カレンダー','法定祝日を自動反映し、学校独自休業日・振替休業日・土曜授業日・特別授業日を追加できます。',`<span class="chip info">祝日ルール ${esc(state.calendar.holidayRuleVersion)}</span>`)+
  `<div class="grid cols2">${card('学期・授業日計算範囲',`<div class="table-wrap"><table class="table"><thead><tr><th>学期</th><th>開始</th><th>終了</th></tr></thead><tbody>${state.calendar.terms.map((t,i)=>`<tr><td>${input(`calendar.terms.${i}.name`,t.name)}</td><td>${input(`calendar.terms.${i}.start`,t.start,'date','data-rerender')}</td><td>${input(`calendar.terms.${i}.end`,t.end,'date','data-rerender')}</td></tr>`).join('')}</tbody></table></div><div class="help" style="margin-top:7px">始業式・終業式等を授業日に数える場合は、その日を計算範囲に含め、必要に応じ行事を登録してください。</div>`) }
  ${card('学校カレンダー例外',`<div class="inline"><button class="btn primary" data-action="addCalendarException">＋ 休業・土曜授業を追加</button><button class="btn" data-action="addEvent">＋ 学校行事を追加</button></div><div class="table-wrap" style="margin-top:10px;max-height:270px"><table class="table"><thead><tr><th>日付</th><th>区分</th><th>名称</th><th></th></tr></thead><tbody>${(state.calendar.exceptions||[]).sort((a,b)=>a.date.localeCompare(b.date)).map((x,i)=>`<tr><td>${esc(x.date)}</td><td>${esc(typeLabel(x.type))}</td><td>${esc(x.label||'')}</td><td><button class="btn small danger" data-action="removeException" data-id="${x.id}">削除</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">学校独自の例外日は未登録です。</td></tr>'}</tbody></table></div>`)}
  </div><div style="height:12px"></div>
  ${card('年度カレンダー',`<div class="calendar-grid">${months.join('')}</div>`,'緑：授業日、赤：国民の祝日、黄：学校休業、青枠：土曜・特別授業、点：学校行事')}`;
}
function renderMiniMonth(y,m,stats){const mat=monthMatrix(y,m);return `<div class="month-card"><h4>${y}年${m+1}月</h4><div class="month-body"><div class="month-kpi"><span>授業日</span><strong>${stats.byMonth[`${y}-${String(m+1).padStart(2,'0')}`]||0}日</strong></div><div class="mini-cal">${['月','火','水','木','金','土','日'].map(x=>`<div class="dow">${x}</div>`).join('')}${mat.map(({date,inMonth})=>{const k=isoDate(date),x=stats.byDate[k],ev=(state.calendar.events||[]).some(e=>e.date===k);let cls='day';if(!inMonth)cls+=' out';else if(x?.exception&&['saturday_instruction','special_instruction','national_override_on'].includes(x.exception.type))cls+=' instruction special';else if(x?.exception&&!x.instruction)cls+=' schooloff';else if(x?.holiday&&!x.instruction)cls+=' holiday';else if(x?.instruction)cls+=' instruction';else if(date.getDay()===0||date.getDay()===6)cls+=' weekend';if(ev)cls+=' event';return `<div class="${cls}" title="${attr(x?.holiday||x?.exception?.label||x?.reason||'')}">${date.getDate()}</div>`}).join('')}</div></div></div>`}

function renderDays(){
  const stats=calendarStats(state),patterns=gradePatterns(state,stats),stdMin=standardUnitMinutesForSchool(state.school.type),actualMin=Number(state.school.lessonMinutes||stdMin);
  return pageHead('04 授業日数・週コマ数','年間授業日数から授業週数を求め、年間計画時数を割って基準週コマ数を自動算出します。')+
  `<div class="grid cols4">${metric('年間授業日数',stats.instructionDays,'日','学期範囲・祝日・学校例外を反映')}${metric('授業週換算',stats.weeks.toFixed(1),'週','授業日数 ÷ 5')}${metric('標準1単位時間',stdMin,'分',state.school.type==='elementary'?'小学校基準':'中学校基準')}${metric('実施1コマ',actualMin,'分',actualMin===stdMin?'標準どおり':'時数を分数換算')}</div><div style="height:12px"></div><div class="notice ${actualMin===stdMin?'ok':'warn'}">標準授業時数は「単位時間」で管理します。実施時間が標準と異なる場合、必要コマ数 = 標準時数 × ${stdMin} ÷ ${actualMin} を切り上げて時間割へ反映します。</div><div style="height:12px"></div>
  ${card('週コマ数の設定',`<div class="form-grid">${field('計算方式',select('instruction.manualWeeklyTarget',state.instruction.manualWeeklyTarget?'true':'false',[['false','年間時数から自動計算'],['true','学校で週コマ数を指定']],'data-boolean data-rerender'),'span4')}${field('手動週コマ数',input('instruction.weeklyTargetOverride',state.instruction.weeklyTargetOverride??'','number','data-number data-rerender'),'span3')}${field('時間割サイクル',select('timetable.cycleWeeks',state.timetable.cycleWeeks,[[1,'1週'],[2,'2週'],[3,'3週']],'data-number data-rerender'),'span3')}${field('1日最大時限',select('instruction.maxPeriods',state.instruction.maxPeriods,[[5,'5限'],[6,'6限'],[7,'7限']],'data-number data-rerender'),'span2')}</div>`)}
  <div style="height:12px"></div>
  ${card('学年別の自動計算',`<div class="table-wrap"><table class="table"><thead><tr><th>学年</th><th>標準年間時数</th><th>実施必要コマ</th><th>週平均</th><th>基準週</th><th>サイクル別</th><th>曜日配当</th></tr></thead><tbody>${state.hourPlans.map(p=>{const w=weeklyTargetForGrade(state,p.grade,stats);return `<tr><td>${p.grade}年</td><td class="num">${w.standardAnnual}</td><td class="num"><strong>${w.annual}</strong></td><td class="num">${w.avg.toFixed(2)}</td><td class="num"><strong>${w.base}</strong></td><td>${w.targets.map((x,i)=>`${i+1}週:${x}`).join(' / ')}</td><td>${(patterns[p.grade]?.[0]||[]).map((x,i)=>`${DAYS[i]}${x}`).join('・')}</td></tr>`}).join('')}</tbody></table></div><div class="notice info" style="margin-top:10px">生徒の時間割は中抜けを作らず、例えば5コマの日は1〜5限に授業を入れ、6限を空きにします。</div>`)} `;
}

function renderHours(){
  const stats=calendarStats(state);
  return pageHead('05 授業時数','学年別の標準授業時数（小学校45分・中学校50分を1単位時間）を管理します。実施1コマの分数が異なる場合は必要コマ数へ自動換算します。')+
  `<div class="grid">${state.hourPlans.map((p,pi)=>{const w=weeklyTargetForGrade(state,p.grade,stats);return card(`${p.grade}年`, `<div class="inline" style="margin-bottom:9px"><span class="chip info">標準年間 ${p.annualTarget}単位</span><span class="chip ${w.lessonMinutes===w.standardMinutes?'ok':'warn'}">実施 ${w.annual}コマ</span><span class="chip neutral">週平均 ${w.avg.toFixed(2)}</span></div><div class="table-wrap"><table class="table"><thead><tr><th>教科等</th><th>標準時数</th><th>調整</th><th>調整後標準時数</th><th>実施必要コマ</th></tr></thead><tbody>${p.subjects.map((s,si)=>{const adjusted=n(s.hours)+n(s.adjustment);return `<tr><td>${esc(s.name)}</td><td>${input(`hourPlans.${pi}.subjects.${si}.hours`,s.hours,'number','data-number data-rerender')}</td><td>${input(`hourPlans.${pi}.subjects.${si}.adjustment`,s.adjustment||0,'number','data-number data-rerender')}</td><td class="num"><strong>${adjusted}</strong></td><td class="num"><strong>${implementationPeriodsForStandardUnits(state,adjusted,p.grade)}</strong></td></tr>`}).join('')}<tr class="total"><td>合計</td><td class="num">${p.subjects.reduce((a,s)=>a+n(s.hours),0)}</td><td class="num">${p.subjects.reduce((a,s)=>a+n(s.adjustment),0)}</td><td class="num">${p.subjects.reduce((a,s)=>a+n(s.hours)+n(s.adjustment),0)}</td><td class="num">${implementationPeriodsForStandardUnits(state,p.subjects.reduce((a,s)=>a+n(s.hours)+n(s.adjustment),0),p.grade)}</td></tr></tbody></table></div><div class="form-grid" style="margin-top:8px">${field('年間標準時数（目標）',input(`hourPlans.${pi}.annualTarget`,p.annualTarget,'number','data-number data-rerender'),'span3',`標準1単位=${w.standardMinutes}分 / 実施1コマ=${w.lessonMinutes}分`)}</div>`)}).join('')}</div>`;
}

function renderIntegrated(){
  const events=state.calendar.events||[];
  return pageHead('06 総合・特別活動','総合的な学習の時間と学校行事の関連を記録し、年間カレンダーと照合します。')+
  `${card('総合的な学習の時間',`<div class="table-wrap"><table class="table"><thead><tr><th>学年</th><th>テーマ</th><th>計画時数</th><th>関連行事</th><th></th></tr></thead><tbody>${state.integrated.plans.map((p,i)=>`<tr><td>${select(`integrated.plans.${i}.grade`,p.grade,[[1,'1年'],[2,'2年'],[3,'3年']],'data-number')}</td><td>${input(`integrated.plans.${i}.title`,p.title)}</td><td>${input(`integrated.plans.${i}.hours`,p.hours,'number','data-number')}</td><td>${esc((p.linkedEventIds||[]).map(id=>events.find(e=>e.id===id)?.name).filter(Boolean).join('、')||'未設定')}</td><td><button class="btn small" data-action="editIntegrated" data-index="${i}">関連付け</button> <button class="btn small danger" data-action="removeIntegrated" data-index="${i}">削除</button></td></tr>`).join('')}</tbody></table></div><div style="margin-top:9px"><button class="btn" data-action="addIntegrated">＋ 計画を追加</button></div>`)}
  <div style="height:12px"></div>
  ${card('学校行事',`<div class="table-wrap"><table class="table"><thead><tr><th>日付</th><th>行事名</th><th>区分</th><th>授業日扱い</th><th></th></tr></thead><tbody>${events.map(e=>`<tr><td>${esc(e.date)}</td><td>${esc(e.name)}</td><td>${esc(e.category||'')}</td><td>${e.countsAsInstruction?'○':'-'}</td><td><button class="btn small danger" data-action="removeEvent" data-id="${e.id}">削除</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">行事未登録</td></tr>'}</tbody></table></div>`)}`;
}

function renderPeriods(){
  return pageHead('07 校時表','授業時限と開始・終了時刻を設定します。時間割編成の最大時限はSTEP04で設定します。')+
  `${card('校時表',`<div class="table-wrap"><table class="table"><thead><tr><th>時限名</th><th>開始</th><th>終了</th><th></th></tr></thead><tbody>${state.periods.map((p,i)=>`<tr><td>${input(`periods.${i}.name`,p.name)}</td><td>${input(`periods.${i}.start`,p.start,'time')}</td><td>${input(`periods.${i}.end`,p.end,'time')}</td><td><button class="btn small danger" data-action="removePeriod" data-index="${i}">削除</button></td></tr>`).join('')}</tbody></table></div><div style="margin-top:9px"><button class="btn" data-action="addPeriod">＋ 時限を追加</button></div>`)} `;
}

function renderResources(){
  const tab=state.ui.resourceTab||'classes';
  const tabs=[['classes','学級'],['teachers','教員'],['facilities','教室・施設'],['lessons','授業設定']];
  let body='';
  if(tab==='classes')body=renderClasses();if(tab==='teachers')body=renderTeachers();if(tab==='facilities')body=renderFacilities();if(tab==='lessons')body=renderLessons();
  return pageHead('08 時間割データ','学級・教員・施設・授業を設定します。TT、合同授業、選択・展開授業、同時展開にも対応します。')+
  `<div class="tabs">${tabs.map(([id,l])=>`<button class="${tab===id?'active':''}" data-action="resourceTab" data-tab="${id}">${l}</button>`).join('')}</div>${body}`;
}
function renderClasses(){return card('学級',`<div class="table-wrap"><table class="table"><thead><tr><th>学年</th><th>学級名</th><th>ID</th><th></th></tr></thead><tbody>${state.resources.classes.map((c,i)=>`<tr><td>${input(`resources.classes.${i}.grade`,c.grade,'number','data-number data-rerender')}</td><td>${input(`resources.classes.${i}.name`,c.name)}</td><td class="mono">${esc(c.id)}</td><td><button class="btn small danger" data-action="removeClass" data-id="${c.id}">削除</button></td></tr>`).join('')}</tbody></table></div><div style="margin-top:9px"><button class="btn" data-action="addClass">＋ 学級を追加</button></div>`)}
function renderTeachers(){return card('教員',`<div class="table-wrap"><table class="table"><thead><tr><th>氏名</th><th>役割</th><th>担当可能教科</th><th>1日上限</th><th>連続上限</th><th>個別条件</th><th></th></tr></thead><tbody>${state.resources.teachers.map((t,i)=>`<tr><td>${input(`resources.teachers.${i}.name`,t.name)}</td><td>${input(`resources.teachers.${i}.role`,t.role||'')}</td><td>${input(`resources.teachers.${i}.subjectsText`,(t.subjects||[]).join('、'))}</td><td>${input(`resources.teachers.${i}.maxDaily`,t.maxDaily,'number','data-number')}</td><td>${input(`resources.teachers.${i}.maxConsecutive`,t.maxConsecutive,'number','data-number')}</td><td><button class="btn small" data-action="teacherConstraints" data-id="${t.id}">禁制・休暇・休憩</button></td><td><button class="btn small danger" data-action="removeTeacher" data-id="${t.id}">削除</button></td></tr>`).join('')}</tbody></table></div><div style="margin-top:9px"><button class="btn" data-action="addTeacher">＋ 教員を追加</button></div>`,'半休・全休、授業不可時間、休憩確保、連続授業上限などを教員ごとに設定できます。')}
function renderFacilities(){return card('教室・施設',`<div class="table-wrap"><table class="table"><thead><tr><th>名称</th><th>種別</th><th>同時利用上限</th><th>利用不可</th><th></th></tr></thead><tbody>${state.resources.facilities.map((f,i)=>`<tr><td>${input(`resources.facilities.${i}.name`,f.name)}</td><td>${select(`resources.facilities.${i}.kind`,f.kind,[['room','教室'],['facility','共有施設']])}</td><td>${input(`resources.facilities.${i}.capacity`,f.capacity,'number','data-number')}</td><td><button class="btn small" data-action="facilityConstraints" data-id="${f.id}">設定 ${(f.unavailable||[]).length}件</button></td><td><button class="btn small danger" data-action="removeFacility" data-id="${f.id}">削除</button></td></tr>`).join('')}</tbody></table></div><div style="margin-top:9px"><button class="btn" data-action="addFacility">＋ 施設を追加</button></div>`,'体育館等を「同時利用上限1」にすると、学年・学級をまたいだ重複をHARD制約で防ぎます。')}
function renderLessons(){
  const stats=calendarStats(state);return card('授業設定',`<div class="toolbar"><button class="btn primary" data-action="addLesson">＋ 授業を追加</button><button class="btn" data-action="exportLessonCsv">CSV出力</button><button class="btn" data-action="importLessonCsv">CSV読込</button><span class="muted">年間時数からサイクル必要コマ数を自動算出</span></div><div class="table-wrap"><table class="table"><thead><tr><th>授業</th><th>学級</th><th>担当</th><th>施設</th><th>形態</th><th>年間</th><th>${state.timetable.cycleWeeks}週必要</th><th>同時展開</th><th></th></tr></thead><tbody>${state.lessons.map(l=>`<tr><td><strong>${esc(l.subject)}</strong></td><td>${esc((l.classIds||[]).map(id=>classById(state,id)?.name||id).join('・'))}</td><td>${esc((l.teacherIds||[]).filter(Boolean).map(id=>teacherById(state,id)?.name||id).join('・')||'未定')}</td><td>${esc(facilityById(state,l.facilityId)?.name||l.facilityId||'未定')}</td><td>${esc(l.type)}</td><td class="num">${n(l.annualHours)}</td><td class="num"><strong>${cycleSessionsForLesson(state,l,stats.instructionDays)}</strong></td><td>${esc(l.syncGroup||'-')}</td><td><button class="btn small" data-action="editLesson" data-id="${l.id}">編集</button> <button class="btn small danger" data-action="removeLesson" data-id="${l.id}">削除</button></td></tr>`).join('')}</tbody></table></div>`,'通常授業のほか、TT・合同・選択・展開・通級等を複数教員／複数学級／同時展開グループで表現できます。')
}

function renderTimetable(){
  const model=buildSolverModel(state),view=state.timetable.view||{kind:'class',id:state.resources.classes[0]?.id,week:0};
  if(view.week>=state.timetable.cycleWeeks)view.week=0;
  const opts=view.kind==='class'?state.resources.classes:view.kind==='teacher'?state.resources.teachers:state.resources.facilities;
  if(!opts.some(x=>x.id===view.id))view.id=opts[0]?.id||'';
  const counts=new Map();for(const p of state.timetable.placements||[])counts.set(p.lessonId,(counts.get(p.lessonId)||0)+1);
  const remaining=state.lessons.map(l=>({l,req:model.lessons.find(x=>x.id===l.id)?.sessionsCycle||0,left:Math.max(0,(model.lessons.find(x=>x.id===l.id)?.sessionsCycle||0)-(counts.get(l.id)||0))})).filter(x=>x.left>0);
  const met=metricsCache||{score:'-',hard:[],unplaced:remaining.reduce((a,x)=>a+x.left,0),soft:0};
  const selected=state.timetable.selectedPlacementId?(state.timetable.placements||[]).find(x=>x.id===state.timetable.selectedPlacementId):null;
  return pageHead('09 時間割編成','入れにくい授業から優先して配置し、HARD制約を守りながら複数回探索します。手動ドラッグ、固定、Undo/Redoにも対応します。',`<span class="chip ${met.hard?.length?'err':met.unplaced?'warn':'ok'}">HARD ${met.hard?.length||0}</span><span class="chip info">未配置 ${met.unplaced||0}</span>`)+
  `<div class="toolbar no-print"><button class="btn primary" data-action="autoSchedule" data-mode="rebuild" ${busy?'disabled':''}>${busy?'編成中…':'スマート編成'}</button><button class="btn blue" data-action="autoSchedule" data-mode="fill" ${busy?'disabled':''}>未配置を補完</button><button class="btn" data-action="undoSchedule" ${!(state.timetable.undo||[]).length?'disabled':''}>↶ Undo</button><button class="btn" data-action="redoSchedule" ${!(state.timetable.redo||[]).length?'disabled':''}>↷ Redo</button><div class="spacer"></div>
  <div class="segmented">${[['class','学級'],['teacher','教員'],['facility','施設']].map(([k,l])=>`<button data-action="scheduleViewKind" data-kind="${k}" class="${view.kind===k?'active':''}">${l}</button>`).join('')}</div>
  <select data-action="scheduleViewId">${opts.map(x=>`<option value="${x.id}" ${x.id===view.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select>
  <div class="segmented">${Array.from({length:state.timetable.cycleWeeks},(_,w)=>`<button data-action="scheduleWeek" data-week="${w}" class="${view.week===w?'active':''}">${w+1}週</button>`).join('')}</div></div>
  <div class="timetable-shell">
    <div class="panel"><div class="panel-head"><h3>未配置授業</h3><span class="badge warn right">${remaining.reduce((a,x)=>a+x.left,0)}駒</span></div><div class="panel-body"><div class="remaining-list">${remaining.map(x=>`<div class="lesson-card" draggable="true" data-drag-lesson="${x.l.id}"><span class="count">×${x.left}</span><div class="title">${esc(x.l.subject)}</div><div class="meta">${esc((x.l.classIds||[]).map(id=>classById(state,id)?.name||id).join('・'))}<br>${esc((x.l.teacherIds||[]).filter(Boolean).map(id=>teacherById(state,id)?.name||id).join('・')||'担当未定')} / ${esc(facilityById(state,x.l.facilityId)?.name||'施設未定')}</div></div>`).join('')||'<div class="notice ok">必要駒はすべて配置されています。</div>'}</div></div></div>
    <div class="panel"><div class="panel-head"><h3>${esc(viewDisplayName(view))}｜${view.week+1}週目</h3><span class="muted right">ドラッグ＆ドロップで配置・移動</span></div><div class="panel-body">${renderTimetableBoard(model,view)}</div></div>
    <div class="panel"><div class="panel-head"><h3>編成状態</h3></div><div class="panel-body"><div class="score"><span class="n">${met.score??'-'}</span><span class="unit">/ 100</span></div><div class="kpi-line"><span>HARD違反</span><strong>${met.hard?.length||0}</strong></div><div class="kpi-line"><span>未配置</span><strong>${met.unplaced||0}</strong></div><div class="kpi-line"><span>SOFTコスト</span><strong>${Math.round(met.soft||0)}</strong></div>
      <div style="height:10px"></div>${selected?renderSelectedPlacement(selected):'<div class="notice info">時間割上の授業をクリックすると、固定・解除・駒外しができます。</div>'}
      <div style="height:10px"></div><h4>主要制約</h4><div class="constraint-list"><div class="constraint"><span class="badge hard">HARD</span> 生徒の中抜け禁止<div class="meta">空きコマは日末側へ</div></div><div class="constraint"><span class="badge hard">HARD</span> 教員・学級・施設重複<div class="meta">休暇・禁制・連続上限を含む</div></div><div class="constraint"><span class="badge soft">SOFT</span> 教科分散・休憩確保<div class="meta">設定に応じて評価</div></div></div>
    </div>
  </div>`;
}
function viewDisplayName(v){if(v.kind==='class')return classById(state,v.id)?.name||v.id;if(v.kind==='teacher')return teacherById(state,v.id)?.name||v.id;return facilityById(state,v.id)?.name||v.id}
function renderTimetableBoard(model,view){
  const max=Math.min(state.periods.length,state.instruction.maxPeriods);let h='<div class="timetable"><div class="tt-head"></div>'+DAYS.map(x=>`<div class="tt-head">${x}</div>`).join('');
  const cmodel=model.classes.find(x=>x.id===view.id);
  for(let p=0;p<max;p++){h+=`<div class="tt-period">${esc(state.periods[p]?.name||`${p+1}限`)}</div>`;for(let d=0;d<5;d++){let allowed=true;if(view.kind==='class')allowed=p<Number(cmodel?.patterns?.[view.week]?.[d]??max);const ps=placementsForViewCell(view,view.week,d,p);h+=`<div class="tt-cell ${allowed?'allowed':'trailing'}" data-drop="1" data-week="${view.week}" data-day="${d}" data-period="${p}">${ps.map(x=>renderPlacementItem(x)).join('')}</div>`} }return h+'</div>';
}
function placementsForViewCell(view,w,d,p){return (state.timetable.placements||[]).filter(x=>{if(x.week!==w||x.day!==d||x.period!==p)return false;const l=lessonById(state,x.lessonId);if(!l)return false;if(view.kind==='class')return l.classIds?.includes(view.id);if(view.kind==='teacher')return (x.teacherIdsOverride?.length?x.teacherIdsOverride:l.teacherIds||[]).includes(view.id);return (x.facilityIdOverride!==undefined?x.facilityIdOverride:l.facilityId)===view.id})}
function renderPlacementItem(p){const l=lessonById(state,p.lessonId);if(!l)return '';const cls=(l.classIds||[]).map(id=>classById(state,id)?.name||id).join('・'),teachers=(p.teacherIdsOverride?.length?p.teacherIdsOverride:l.teacherIds||[]).filter(Boolean).map(id=>teacherById(state,id)?.name||id).join('・');return `<div class="tt-item ${p.locked?'locked':''} ${state.timetable.selectedPlacementId===p.id?'selected':''}" draggable="true" data-drag-placement="${p.id}" data-action="selectPlacement" data-id="${p.id}"><div class="subj">${esc(l.subject)}</div><div class="meta">${esc(cls)}${teachers?` / ${esc(teachers)}`:''}</div><div class="flags">${p.locked?'<span class="badge hard">固定</span>':''}${l.syncGroup?'<span class="badge info">同時展開</span>':''}${p.teacherIdsOverride?.length?'<span class="badge warn">代替</span>':''}</div></div>`}
function renderSelectedPlacement(p){const l=lessonById(state,p.lessonId);return `<div class="card flat"><h4>選択中：${esc(l?.subject||'')}</h4><div class="sub">${DAYS[p.day]}曜 ${p.period+1}限 / ${p.week+1}週</div><div class="inline"><button class="btn small" data-action="toggleLock" data-id="${p.id}">${p.locked?'固定解除':'固定'}</button><button class="btn small danger" data-action="removePlacement" data-id="${p.id}">駒を外す</button></div></div>`}

function renderOperations(){
  const cache=absenceCache;return pageHead('10 臨時変更・欠勤対応','基本時間割は変更せず、欠勤・行事等による一日限りの変更案を作り、臨時時間割として保存します。')+
  `<div class="grid cols2">${card('教員欠勤リプラン',`<div class="form-grid">${field('欠勤教員',`<select id="absenceTeacher">${state.resources.teachers.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select>`,'span5')}${field('サイクル週',`<select id="absenceWeek">${Array.from({length:state.timetable.cycleWeeks},(_,i)=>`<option value="${i}">${i+1}週</option>`).join('')}</select>`,'span3')}${field('曜日',`<select id="absenceDay">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select>`,'span4')}${field('実施日（記録用）','<input type="date" id="absenceDate">','span5')}</div><div class="inline" style="margin-top:10px"><button class="btn primary" data-action="generateAbsence" ${busy?'disabled':''}>変更案を作成</button></div><div class="help" style="margin-top:8px">代替教員候補と、同一学級内の授業交換を探索して複数案を比較します。基本時間割は上書きしません。</div>`) }
  ${card('臨時時間割',`<div class="inline"><button class="btn" data-action="createTemporary">＋ 基本時間割から作成</button></div><div class="table-wrap" style="margin-top:10px"><table class="table"><thead><tr><th>日付</th><th>名称</th><th>変更内容</th><th></th></tr></thead><tbody>${(state.operations.temporarySchedules||[]).map(x=>`<tr><td>${esc(x.date||'-')}</td><td>${esc(x.label)}</td><td>${esc((x.changes||[]).map(c=>c.text).join(' / ')||'基本時間割を複製')}</td><td><button class="btn small" data-action="viewTemporary" data-id="${x.id}">確認</button> <button class="btn small danger" data-action="removeTemporary" data-id="${x.id}">削除</button></td></tr>`).join('')||'<tr><td colspan="4" class="muted">臨時時間割は未作成です。</td></tr>'}</tbody></table></div>`)}
  </div>${cache?`<div style="height:12px"></div>${renderAbsenceResults(cache)}`:''}`;
}
function renderAbsenceResults(cache){
  if(!cache.affected?.length)return card('欠勤影響','<div class="notice ok">指定した教員はこの曜日に授業がありません。</div>');
  return card('変更案',`<div class="notice info">影響する授業：${cache.affected.length}件。案を採用すると「臨時時間割」として保存され、基本時間割はそのまま残ります。</div><div class="grid cols2" style="margin-top:10px">${cache.proposals.map((p,i)=>`<div class="card flat"><div class="inline"><h4>${esc(p.title)}</h4><span class="badge ${p.ok?'ok':'warn'} right">${p.ok?'成立':'要手動調整'}</span></div>${p.changes.map(c=>`<div class="constraint"><strong>${esc(c.type)}</strong><div class="meta">${esc(c.text)}</div></div>`).join('')}<div class="kpi-line"><span>HARD</span><strong>${p.metrics.hard.length}</strong></div><button class="btn ${p.ok?'green':'warn'}" data-action="applyAbsenceProposal" data-index="${i}" ${p.ok?'':'disabled'}>この案を臨時時間割に保存</button></div>`).join('')}</div>`);
}

function renderChecks(){
  const stats=calendarStats(state),issues=[...validateState(state,stats)];if(metricsCache){for(const h of metricsCache.hard||[])issues.push({level:'ERROR',code:'TT-HARD',title:'時間割HARD制約',desc:h.text});if(metricsCache.unplaced)issues.push({level:'ERROR',code:'TT-UNPLACED',title:'未配置授業があります',desc:`残り${metricsCache.unplaced}駒を配置してください。`});if((metricsCache.soft||0)>40)issues.push({level:'WARNING',code:'TT-SOFT',title:'時間割の配慮条件が多く残っています',desc:`SOFTコスト ${Math.round(metricsCache.soft)}。配置を確認してください。`})}
  const ec={ERROR:issues.filter(x=>x.level==='ERROR').length,WARNING:issues.filter(x=>x.level==='WARNING').length,INFO:issues.filter(x=>x.level==='INFO').length};
  return pageHead('11 最終チェック','制度・入力整合・時間割成立性をまとめて確認します。ERRORは校内確定前に解消する想定です。',`<span class="chip ${ec.ERROR?'err':'ok'}">ERROR ${ec.ERROR}</span><span class="chip ${ec.WARNING?'warn':'ok'}">WARNING ${ec.WARNING}</span>`)+
  `<div class="grid cols3">${metric('ERROR',ec.ERROR,'件')}${metric('WARNING',ec.WARNING,'件')}${metric('時間割スコア',metricsCache?.score??'-','/100')}</div><div style="height:12px"></div>${card('確認事項',`<div class="issue-list">${issues.map(x=>`<div class="issue"><span class="badge ${x.level==='ERROR'?'err':x.level==='WARNING'?'warn':'info'}">${x.level}</span><div><div class="title">${esc(x.title)}</div><div class="desc">${esc(x.desc)}</div></div><div class="code mono">${esc(x.code)}</div></div>`).join('')||'<div class="notice ok">現在、確認事項はありません。</div>'}</div>`)}`;
}

function renderReports(){
  const type=state.ui.reportType||'summary';return pageHead('12 帳票・保存','教育課程概要、年間カレンダー、授業時数、時間割を印刷/PDF保存できます。端末・Driveへのバックアップもここで管理します。')+
  `<div class="grid cols3"><div class="card"><h3>帳票</h3><div class="field"><label>帳票種類</label><select id="reportType" data-action="reportType">${[['summary','教育課程編成概要'],['calendar','年間カレンダー'],['hours','授業時数配当表'],['timetable','時間割表'],['teachers','教員時間割一覧'],['facilities','施設時間割一覧']].map(([v,l])=>`<option value="${v}" ${type===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="inline" style="margin-top:10px"><button class="btn primary" data-action="printReport">印刷 / PDF</button><button class="btn" data-action="exportJson">JSON</button></div></div>
  <div class="card"><h3>Google Drive</h3><div class="kpi-line"><span>最終同期</span><strong>${fmtTime(state.drive.lastSyncAt)}</strong></div><div class="inline" style="margin-top:10px"><button class="btn" data-action="openDrive">Drive設定・同期</button></div></div>
  <div class="card"><h3>ローカルデータ</h3><div class="kpi-line"><span>自動保存</span><strong>IndexedDB</strong></div><div class="inline" style="margin-top:10px"><button class="btn" data-action="importJson">バックアップを復元</button><button class="btn danger" data-action="resetAll">初期化</button></div></div></div>
  <div style="height:12px"></div><div class="card"><div class="toolbar"><strong>プレビュー</strong><span class="muted">ブラウザの印刷からPDF保存できます。</span></div><div id="reportPreview" style="overflow:auto"></div></div>`;
}
function renderReportPreview(){const el=$('#reportPreview');if(!el)return;const type=state.ui.reportType||'summary';let opts={};if(type==='timetable')opts={kind:state.timetable.view.kind,id:state.timetable.view.id};el.innerHTML=reportByType(state,type,opts)}

function openModal(title,body,buttons=''){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop" data-action="closeModal"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>${esc(title)}</h3><button class="btn icon" data-action="closeModal">×</button></div><div class="modal-body">${body}</div>${buttons?`<div class="modal-foot">${buttons}</div>`:''}</div></div>`}
function closeModal(){$('#modalRoot').innerHTML=''}
function selectedValues(name){return $$(`[name="${name}"]:checked`).map(x=>x.value)}
function gridUnavailable(values=[],prefix='u'){const max=Math.min(state.periods.length,state.instruction.maxPeriods);return `<div class="table-wrap"><table class="table"><thead><tr><th>時限</th>${DAYS.map(d=>`<th>${d}</th>`).join('')}</tr></thead><tbody>${Array.from({length:max},(_,p)=>`<tr><th>${p+1}限</th>${DAYS.map((d,day)=>{const k=`${day}-${p}`;return `<td class="center"><input type="checkbox" name="${prefix}" value="${k}" ${values.includes(k)?'checked':''}></td>`}).join('')}</tr>`).join('')}</tbody></table></div>`}

async function handleClick(e){
  const nav=e.target.closest('[data-nav]');if(nav){state.ui.page=nav.dataset.nav;scheduleSave();render();return}
  const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
  try{
    if(a==='closeModal'){closeModal();return}
    if(a==='openDrive'){showDriveModal();return}
    if(a==='exportJson'){const name=`${(state.school.name||'school').replace(/\s/g,'_')}_${state.school.fiscalYear}_curriculum.json`;downloadText(name,JSON.stringify(state,null,2));toast('JSONバックアップを保存しました','ok');return}
    if(a==='importJson'){importJsonDialog();return}
    if(a==='addFocus'){state.goals.focusItems.push({id:uid('focus'),label:'新しい重点',text:''});scheduleSave();render();return}
    if(a==='removeFocus'){state.goals.focusItems.splice(Number(b.dataset.index),1);scheduleSave();render();return}
    if(a==='addCalendarException'){showCalendarExceptionModal();return}
    if(a==='removeException'){state.calendar.exceptions=state.calendar.exceptions.filter(x=>x.id!==b.dataset.id);scheduleSave();render();return}
    if(a==='addEvent'){showEventModal();return}
    if(a==='removeEvent'){state.calendar.events=state.calendar.events.filter(x=>x.id!==b.dataset.id);for(const p of state.integrated.plans)p.linkedEventIds=(p.linkedEventIds||[]).filter(id=>id!==b.dataset.id);scheduleSave();render();return}
    if(a==='addIntegrated'){state.integrated.plans.push({id:uid('int'),grade:1,title:'',hours:50,linkedEventIds:[]});scheduleSave();render();return}
    if(a==='removeIntegrated'){state.integrated.plans.splice(Number(b.dataset.index),1);scheduleSave();render();return}
    if(a==='editIntegrated'){showIntegratedModal(Number(b.dataset.index));return}
    if(a==='addPeriod'){state.periods.push({id:uid('p'),name:`${state.periods.length+1}限`,start:'',end:''});state.instruction.maxPeriods=Math.min(state.periods.length,7);scheduleSave();render();return}
    if(a==='removePeriod'){if(state.periods.length<=1)return toast('時限は1つ以上必要です','warn');state.periods.splice(Number(b.dataset.index),1);state.instruction.maxPeriods=Math.min(state.instruction.maxPeriods,state.periods.length);scheduleSave();render();return}
    if(a==='resourceTab'){state.ui.resourceTab=b.dataset.tab;scheduleSave();render();return}
    if(a==='addClass'){state.resources.classes.push({id:uid('c'),grade:1,name:'新規学級'});scheduleSave();render();return}
    if(a==='removeClass'){const id=b.dataset.id;if(state.lessons.some(l=>l.classIds?.includes(id)))return toast('授業設定で使用中の学級は削除できません','warn');state.resources.classes=state.resources.classes.filter(x=>x.id!==id);scheduleSave();render();return}
    if(a==='addTeacher'){state.resources.teachers.push({id:uid('t'),name:'新規教員',role:'',subjects:[],unavailable:[],leaves:[],maxDaily:5,maxConsecutive:3,consecutiveHard:false,substituteEligible:true,breakRule:{enabled:false,startPeriod:3,endPeriod:4,minFreeSlots:1,hard:false}});scheduleSave();render();return}
    if(a==='removeTeacher'){const id=b.dataset.id;if(state.lessons.some(l=>l.teacherIds?.includes(id)))return toast('授業設定で使用中の教員は削除できません','warn');state.resources.teachers=state.resources.teachers.filter(x=>x.id!==id);scheduleSave();render();return}
    if(a==='teacherConstraints'){showTeacherConstraints(b.dataset.id);return}
    if(a==='addFacility'){state.resources.facilities.push({id:uid('f'),name:'新規施設',kind:'facility',capacity:1,unavailable:[]});scheduleSave();render();return}
    if(a==='removeFacility'){const id=b.dataset.id;if(state.lessons.some(l=>l.facilityId===id))return toast('授業設定で使用中の施設は削除できません','warn');state.resources.facilities=state.resources.facilities.filter(x=>x.id!==id);scheduleSave();render();return}
    if(a==='facilityConstraints'){showFacilityConstraints(b.dataset.id);return}
    if(a==='addLesson'){showLessonModal(null);return}
    if(a==='editLesson'){showLessonModal(b.dataset.id);return}
    if(a==='removeLesson'){const id=b.dataset.id;state.lessons=state.lessons.filter(x=>x.id!==id);state.timetable.placements=state.timetable.placements.filter(x=>x.lessonId!==id);scheduleSave();render();refreshMetrics();return}
    if(a==='exportLessonCsv'){exportLessonCsv();return}
    if(a==='importLessonCsv'){importLessonCsvDialog();return}
    if(a==='scheduleViewKind'){state.timetable.view.kind=b.dataset.kind;const opts=b.dataset.kind==='class'?state.resources.classes:b.dataset.kind==='teacher'?state.resources.teachers:state.resources.facilities;state.timetable.view.id=opts[0]?.id||'';scheduleSave();render();return}
    if(a==='scheduleWeek'){state.timetable.view.week=Number(b.dataset.week);scheduleSave();render();return}
    if(a==='selectPlacement'){state.timetable.selectedPlacementId=b.dataset.id;render();return}
    if(a==='autoSchedule'){await runAutoSchedule(b.dataset.mode||'rebuild');return}
    if(a==='toggleLock'){const p=state.timetable.placements.find(x=>x.id===b.dataset.id);if(p){p.locked=!p.locked;scheduleSave();render()}return}
    if(a==='removePlacement'){removePlacementGroup(b.dataset.id);return}
    if(a==='undoSchedule'){undoSchedule();return}
    if(a==='redoSchedule'){redoSchedule();return}
    if(a==='generateAbsence'){await generateAbsence();return}
    if(a==='applyAbsenceProposal'){applyAbsenceProposal(Number(b.dataset.index));return}
    if(a==='createTemporary'){showTemporaryModal();return}
    if(a==='viewTemporary'){showTemporaryDetail(b.dataset.id);return}
    if(a==='removeTemporary'){state.operations.temporarySchedules=state.operations.temporarySchedules.filter(x=>x.id!==b.dataset.id);scheduleSave();render();return}
    if(a==='printReport'){printCurrentReport();return}
    if(a==='resetAll'){if(confirm('端末内データを初期化します。先にJSONバックアップを保存することをおすすめします。')){state=defaultState();await saveState(state);metricsCache=null;absenceCache=null;render();refreshMetrics()}return}
    if(a==='saveDrive'){await doSaveDrive();return}
    if(a==='loadDrive'){await doLoadDrive();return}
  }catch(err){console.error(err);toast(err.message||String(err),'err')}
}
function handleChange(e){
  const path=e.target.dataset.bind;
  if(path==='school.type'){
    const next=e.target.value;
    applySchoolTypeDefaults(state,next);
    metricsCache=null;absenceCache=null;
    scheduleSave();render();refreshMetrics();
    toast(next==='elementary'?'小学校の教科・標準時数・45分基準へ切り替えました':'中学校の教科・標準時数・50分基準へ切り替えました','ok');
    return;
  }
  if(path&&e.target.dataset.rerender!==undefined){state.updatedAt=new Date().toISOString();scheduleSave();render();if(['resources','timetable','days','hours','basic'].includes(state.ui.page))refreshMetrics()}
  const a=e.target.dataset.action;
  if(a==='scheduleViewId'){state.timetable.view.id=e.target.value;scheduleSave();render()}
  if(a==='reportType'){state.ui.reportType=e.target.value;scheduleSave();renderReportPreview()}
}
function handleDragStart(e){const l=e.target.closest('[data-drag-lesson]'),p=e.target.closest('[data-drag-placement]');if(l)e.dataTransfer.setData('application/json',JSON.stringify({type:'lesson',id:l.dataset.dragLesson}));if(p)e.dataTransfer.setData('application/json',JSON.stringify({type:'placement',id:p.dataset.dragPlacement}))}
async function handleDrop(e){const cell=e.target.closest('[data-drop]');if(!cell)return;e.preventDefault();cell.classList.remove('drop-target');let data;try{data=JSON.parse(e.dataTransfer.getData('application/json'))}catch{return}const target={week:Number(cell.dataset.week),day:Number(cell.dataset.day),period:Number(cell.dataset.period)};busy=true;try{if(data.type==='lesson'){const r=await placeLesson(state,data.id,target);if(!r.ok)return toast((r.conflicts||[]).map(x=>x.text).join(' / '),'warn');applyPlacements(r.placements)}else if(data.type==='placement'){const r=await movePlacement(state,data.id,target);if(!r.ok)return toast((r.conflicts||[]).map(x=>x.text).join(' / '),'warn');applyPlacements(r.placements)}}finally{busy=false}}

async function runAutoSchedule(mode){busy=true;render();try{const r=await solveSchedule(state,mode);pushUndo();state.timetable.placements=r.placements;metricsCache=r.metrics;state.timetable.lastResult={at:new Date().toISOString(),mode,metrics:r.metrics};state.updatedAt=new Date().toISOString();scheduleSave();toast(r.metrics.unplaced?`編成しました。未配置 ${r.metrics.unplaced}駒`:'時間割を編成しました','ok')}finally{busy=false;render()}}
function undoSchedule(){const u=state.timetable.undo||[];if(!u.length)return;state.timetable.redo=state.timetable.redo||[];state.timetable.redo.push(deepClone(state.timetable.placements));state.timetable.placements=u.pop();state.timetable.selectedPlacementId=null;scheduleSave();refreshMetrics();render()}
function redoSchedule(){const r=state.timetable.redo||[];if(!r.length)return;state.timetable.undo=state.timetable.undo||[];state.timetable.undo.push(deepClone(state.timetable.placements));state.timetable.placements=r.pop();state.timetable.selectedPlacementId=null;scheduleSave();refreshMetrics();render()}
function removePlacementGroup(id){const p=state.timetable.placements.find(x=>x.id===id);if(!p)return;const l=lessonById(state,p.lessonId);if(p.locked)return toast('固定を解除してから外してください','warn');pushUndo();if(l?.syncGroup){state.timetable.placements=state.timetable.placements.filter(x=>{const q=lessonById(state,x.lessonId);return !(q?.syncGroup===l.syncGroup&&x.week===p.week&&x.day===p.day&&x.period===p.period)})}else state.timetable.placements=state.timetable.placements.filter(x=>x.id!==id);state.timetable.selectedPlacementId=null;scheduleSave();refreshMetrics();render()}
async function generateAbsence(){const tid=$('#absenceTeacher')?.value,w=n($('#absenceWeek')?.value),d=n($('#absenceDay')?.value);if(!tid)return;busy=true;render();try{absenceCache=await absenceProposals(state,tid,w,d);absenceCache.context={teacherId:tid,week:w,day:d,date:$('#absenceDate')?.value||''};state.ui.absenceContext=absenceCache.context;toast(`変更案 ${absenceCache.proposals.length}件を作成しました`,'ok')}finally{busy=false;render()}}
function applyAbsenceProposal(i){const p=absenceCache?.proposals?.[i];if(!p)return;const ctx=absenceCache.context||state.ui.absenceContext||{};state.operations.temporarySchedules.push({id:uid('tmp'),date:ctx.date||'',label:`${teacherById(state,ctx.teacherId)?.name||'教員'} 欠勤対応`,week:ctx.week,day:ctx.day,placements:deepClone(p.placements),changes:deepClone(p.changes),createdAt:new Date().toISOString(),source:'absence'});state.operations.absences.push({id:uid('abs'),...ctx,proposal:p.title,createdAt:new Date().toISOString()});scheduleSave();toast('基本時間割を変更せず、臨時時間割として保存しました','ok');absenceCache=null;render()}

function showCalendarExceptionModal(){openModal('学校カレンダー例外を追加',`<div class="form-grid">${field('日付','<input type="date" id="exDate">','span4')}${field('区分',`<select id="exType"><option value="school_holiday">学校独自休業日</option><option value="substitute_holiday">振替休業日</option><option value="saturday_instruction">土曜授業日</option><option value="special_instruction">特別授業日</option><option value="closed">休業日</option><option value="national_override_off">特例休業日</option><option value="national_override_on">特例授業日</option></select>`,'span4')}${field('名称','<input id="exLabel" placeholder="例：学校公開の振替休業">','span4')}</div><div class="notice info" style="margin-top:10px">法定祝日は自動登録されます。法改正や特例的な休日がある場合は、ここで追加・上書きできます。</div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveCalendarException">追加</button>`)}
function showEventModal(){openModal('学校行事を追加',`<div class="form-grid">${field('日付','<input type="date" id="evDate">','span3')}${field('行事名','<input id="evName">','span5')}${field('区分',`<select id="evCategory"><option>儀式的行事</option><option>文化的行事</option><option>健康安全・体育的行事</option><option>旅行・集団宿泊的行事</option><option>勤労生産・奉仕的行事</option><option>その他</option></select>`,'span4')}${field('授業日扱い','<label class="inline"><input type="checkbox" id="evInstruction" checked> 授業日として数える</label>','span4')}</div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveEvent">追加</button>`)}
function showIntegratedModal(i){const p=state.integrated.plans[i];openModal('総合と学校行事の関連付け',`<div class="notice info">${esc(p.title||'総合的な学習')}</div><div class="grid cols2" style="margin-top:10px">${(state.calendar.events||[]).map(e=>`<label class="constraint"><input type="checkbox" name="intEvents" value="${e.id}" ${(p.linkedEventIds||[]).includes(e.id)?'checked':''}> <strong>${esc(e.date)} ${esc(e.name)}</strong><div class="meta">${esc(e.category||'')}</div></label>`).join('')}</div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveIntegratedLinks" data-index="${i}">保存</button>`)}

function showTeacherConstraints(id){const t=teacherById(state,id);if(!t)return;const leaves=(t.leaves||[]).map((x,i)=>`<tr><td>${x.week==='all'?'毎週':`${Number(x.week)+1}週`}</td><td>${DAYS[x.day]}</td><td>${x.segment}</td><td><button class="btn small danger" data-action="deleteTeacherLeave" data-id="${id}" data-index="${i}">削除</button></td></tr>`).join('');openModal(`${t.name}｜個別条件`,`${card('授業不可時間',gridUnavailable(t.unavailable||[],'teacherUnavailable'),'チェックした時限には通常時間割を配置しません。')}
  <div style="height:10px"></div>${card('半休・全休・研究日',`<div class="table-wrap"><table class="table"><thead><tr><th>適用</th><th>曜日</th><th>区分</th><th></th></tr></thead><tbody>${leaves||'<tr><td colspan="4" class="muted">未設定</td></tr>'}</tbody></table></div><div class="form-grid" style="margin-top:8px">${field('週',`<select id="leaveWeek"><option value="all">毎週</option>${Array.from({length:state.timetable.cycleWeeks},(_,w)=>`<option value="${w}">${w+1}週</option>`).join('')}</select>`,'span4')}${field('曜日',`<select id="leaveDay">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select>`,'span4')}${field('区分',`<select id="leaveSegment"><option value="FULL">全休</option><option value="AM">午前休</option><option value="PM">午後休</option></select>`,'span4')}</div><button class="btn small" data-action="addTeacherLeave" data-id="${id}">＋ 休暇条件を追加</button>`)}
  <div style="height:10px"></div>${card('休憩時間',`<label class="inline"><input type="checkbox" id="breakEnabled" ${t.breakRule?.enabled?'checked':''}> 休憩確保条件を使う</label><div class="form-grid" style="margin-top:8px">${field('対象開始時限',`<input type="number" min="1" max="${state.periods.length}" id="breakStart" value="${n(t.breakRule?.startPeriod,3)+1}">`,'span3')}${field('対象終了時限',`<input type="number" min="1" max="${state.periods.length}" id="breakEnd" value="${n(t.breakRule?.endPeriod,4)+1}">`,'span3')}${field('最低空きコマ',`<input type="number" min="1" id="breakSlots" value="${n(t.breakRule?.minFreeSlots,1)}">`,'span3')}${field('扱い',`<select id="breakHard"><option value="false" ${!t.breakRule?.hard?'selected':''}>配慮条件（SOFT）</option><option value="true" ${t.breakRule?.hard?'selected':''}>厳守条件（HARD）</option></select>`,'span3')}</div><div class="form-grid" style="margin-top:8px">${field('連続授業上限の扱い',`<select id="consecutiveHard"><option value="false" ${!t.consecutiveHard?'selected':''}>できるだけ避ける（SOFT）</option><option value="true" ${t.consecutiveHard?'selected':''}>超過禁止（HARD）</option></select>`,'span4')}${field('欠勤時の代替候補',`<label><input type="checkbox" id="substituteEligible" ${t.substituteEligible!==false?'checked':''}> 自習・課題対応の代替候補に含める</label>`,'span5')}</div>`,'指定した時間帯の中に、最低限の空きコマを確保します。')}`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveTeacherConstraints" data-id="${id}">保存</button>`)}
function showFacilityConstraints(id){const f=facilityById(state,id);if(!f)return;openModal(`${f.name}｜利用不可時間`,gridUnavailable(f.unavailable||[],'facilityUnavailable'),`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveFacilityConstraints" data-id="${id}">保存</button>`)}

function showLessonModal(id){const l=id?lessonById(state,id):{id:uid('l'),subject:'',name:'',classIds:[],teacherIds:[],facilityId:'normal',annualHours:35,cycleSessionsOverride:null,type:'normal',syncGroup:'',allowTeacherTBD:false,allowFacilityTBD:false};const isNew=!id;openModal(isNew?'授業を追加':'授業を編集',`<div class="form-grid">${field('教科・授業名',`<input id="lessonSubject" value="${attr(l.subject||'')}">`,'span5')}${field('形態',`<select id="lessonType">${['normal','TT','joint','elective','parallel','resource','support'].map(x=>`<option value="${x}" ${l.type===x?'selected':''}>${x}</option>`).join('')}</select>`,'span3')}${field('年間時数',`<input type="number" id="lessonHours" value="${n(l.annualHours,35)}">`,'span2')}${field('サイクル駒数上書き',`<input type="number" id="lessonCycle" value="${l.cycleSessionsOverride??''}" placeholder="自動">`,'span2','空欄なら年間時数÷授業週数から自動算出')}
  ${field('対象学級',`<div class="grid cols3">${state.resources.classes.map(c=>`<label class="constraint"><input type="checkbox" name="lessonClasses" value="${c.id}" ${(l.classIds||[]).includes(c.id)?'checked':''}> ${esc(c.name)}</label>`).join('')}</div>`,'span12')}
  ${field('担当教員',`<div class="grid cols3">${state.resources.teachers.map(t=>`<label class="constraint"><input type="checkbox" name="lessonTeachers" value="${t.id}" ${(l.teacherIds||[]).includes(t.id)?'checked':''}> ${esc(t.name)}</label>`).join('')}</div>`,'span12')}
  ${field('使用教室・施設',`<select id="lessonFacility"><option value="">未定</option>${state.resources.facilities.map(f=>`<option value="${f.id}" ${l.facilityId===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select>`,'span5')}${field('同時展開グループ',`<input id="lessonSync" value="${attr(l.syncGroup||'')}" placeholder="例：SEL-G1">`,'span4','同じ文字列の授業を同一時限に配置します。')}${field('仮配置',`<label><input type="checkbox" id="lessonTeacherTBD" ${l.allowTeacherTBD?'checked':''}> 教員未定を許可</label><br><label><input type="checkbox" id="lessonFacilityTBD" ${l.allowFacilityTBD?'checked':''}> 施設未定を許可</label>`,'span3')}
  ${field('授業を置けない時限',gridUnavailable(l.unavailable||[],'lessonUnavailable'),'span12','教科・授業固有の禁制時間です。')}</div><div class="notice info" style="margin-top:10px">TTは複数教員を選択、合同授業は複数学級を1授業に設定、選択・展開授業は複数の授業に同じ「同時展開グループ」を設定します。</div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveLesson" data-id="${l.id}" data-new="${isNew?'1':'0'}">保存</button>`)}

function showTemporaryModal(){openModal('臨時時間割を作成',`<div class="form-grid">${field('日付','<input type="date" id="tmpDate">','span4')}${field('名称','<input id="tmpLabel" placeholder="例：文化祭前日・短縮日課">','span5')}${field('サイクル週',`<select id="tmpWeek">${Array.from({length:state.timetable.cycleWeeks},(_,w)=>`<option value="${w}">${w+1}週</option>`).join('')}</select>`,'span3')}</div><div class="notice info" style="margin-top:10px">基本時間割のコピーを臨時時間割として保存します。欠勤対応案を採用した場合も同じ場所に保存されます。</div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="saveTemporary">作成</button>`)}
function showTemporaryDetail(id){const x=state.operations.temporarySchedules.find(y=>y.id===id);if(!x)return;const ps=x.placements||[];const week=Number(x.week||0);const slotOptions=[];for(let d=0;d<5;d++)for(let p=0;p<Math.min(state.periods.length,state.instruction.maxPeriods);p++)slotOptions.push(`<option value="${d}-${p}">${DAYS[d]} ${p+1}限</option>`);const body=`<div class="notice info">${esc(x.date||'日付未設定')}｜${esc(x.label)}｜${week+1}週パターン</div><div style="margin-top:10px">${(x.changes||[]).map(c=>`<div class="constraint"><strong>${esc(c.type||'変更')}</strong><div class="meta">${esc(c.text||'')}</div></div>`).join('')||'<div class="muted">基本時間割の複製です。</div>'}</div><div class="kpi-line"><span>保存駒数</span><strong>${ps.length}</strong></div>
  <div style="height:10px"></div>${card('臨時の入替',`<div class="form-grid">${field('学級',`<select id="tmpSwapClass">${state.resources.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select>`,'span4')}${field('時限A',`<select id="tmpSlotA">${slotOptions.join('')}</select>`,'span4')}${field('時限B',`<select id="tmpSlotB">${slotOptions.join('')}</select>`,'span4')}</div><button class="btn small" data-action="tempSwap" data-id="${id}">2コマを入替</button>`,'合同・同時展開など複合授業は安全のため自動入替対象外です。')}
  <div style="height:10px"></div>${card('行事・短縮対応',`<div class="form-grid">${field('休止する時限',`<select id="tmpRemoveSlot">${slotOptions.join('')}</select>`,'span6')}</div><div class="inline"><button class="btn small warn" data-action="tempRemoveSlot" data-id="${id}">この時限を休止</button><button class="btn small" data-action="tempRemoveShift" data-id="${id}">休止して後続を前詰め</button></div>`,'学校全体の臨時変更として記録します。')}</div>`;openModal('臨時時間割',body,`<button class="btn" data-action="closeModal">閉じる</button>`)}


function showDriveModal(){openModal('Google Drive 同期',`<div class="notice info">学校の作業データは端末内へ自動保存されます。Driveはバックアップ・端末移行用です。Google認証時のみインターネットへ接続します。</div><div class="form-grid" style="margin-top:10px">${field('OAuth Client ID',`<input id="driveClientId" value="${attr(state.drive.clientId||'')}" placeholder="xxxxxxxx.apps.googleusercontent.com">`,'span8','Google Cloud ConsoleでWebアプリ用Client IDを作成し、このPWAのHTTPS配信元をAuthorized JavaScript originsへ登録します。')}${field('Driveフォルダ名',`<input id="driveFolder" value="${attr(state.drive.folderName||'CurriculumPlanner')}">`,'span4')}</div><div class="kpi-line"><span>最終同期</span><strong>${fmtTime(state.drive.lastSyncAt)}</strong></div><div class="kpi-line"><span>Drive File ID</span><strong class="mono" style="font-size:9px">${esc(state.drive.fileId||'未作成')}</strong></div>`,`<button class="btn" data-action="closeModal">閉じる</button><button class="btn" data-action="loadDrive">Driveから読込</button><button class="btn primary" data-action="saveDrive">Driveへ保存</button>`)}

async function handleSecondaryClick(e){const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;try{
  if(a==='saveCalendarException'){const date=$('#exDate')?.value;if(!date)return toast('日付を指定してください','warn');state.calendar.exceptions.push({id:uid('ex'),date,type:$('#exType').value,label:$('#exLabel').value.trim()});closeModal();scheduleSave();render();return}
  if(a==='saveEvent'){const date=$('#evDate')?.value,name=$('#evName')?.value.trim();if(!date||!name)return toast('日付と行事名を入力してください','warn');state.calendar.events.push({id:uid('ev'),date,name,category:$('#evCategory').value,countsAsInstruction:$('#evInstruction').checked});closeModal();scheduleSave();render();return}
  if(a==='saveIntegratedLinks'){const i=Number(b.dataset.index);state.integrated.plans[i].linkedEventIds=selectedValues('intEvents');closeModal();scheduleSave();render();return}
  if(a==='addTeacherLeave'){const t=teacherById(state,b.dataset.id);if(!t)return;t.leaves.push({week:$('#leaveWeek').value==='all'?'all':Number($('#leaveWeek').value),day:Number($('#leaveDay').value),segment:$('#leaveSegment').value});showTeacherConstraints(t.id);scheduleSave();return}
  if(a==='deleteTeacherLeave'){const t=teacherById(state,b.dataset.id);if(!t)return;t.leaves.splice(Number(b.dataset.index),1);showTeacherConstraints(t.id);scheduleSave();return}
  if(a==='saveTeacherConstraints'){const t=teacherById(state,b.dataset.id);if(!t)return;t.unavailable=selectedValues('teacherUnavailable');t.breakRule={enabled:$('#breakEnabled').checked,startPeriod:Math.max(0,n($('#breakStart').value)-1),endPeriod:Math.max(0,n($('#breakEnd').value)-1),minFreeSlots:Math.max(1,n($('#breakSlots').value,1)),hard:$('#breakHard').value==='true'};t.consecutiveHard=$('#consecutiveHard').value==='true';t.substituteEligible=$('#substituteEligible').checked;closeModal();scheduleSave();refreshMetrics();render();return}
  if(a==='saveFacilityConstraints'){const f=facilityById(state,b.dataset.id);if(!f)return;f.unavailable=selectedValues('facilityUnavailable');closeModal();scheduleSave();refreshMetrics();render();return}
  if(a==='saveLesson'){saveLessonFromModal(b.dataset.id,b.dataset.new==='1');return}
  if(a==='saveTemporary'){const date=$('#tmpDate').value,label=$('#tmpLabel').value.trim()||'臨時時間割',week=Number($('#tmpWeek').value);state.operations.temporarySchedules.push({id:uid('tmp'),date,label,week,day:date?((new Date(date+'T00:00:00').getDay()+6)%7):0,placements:deepClone(state.timetable.placements),changes:[],createdAt:new Date().toISOString(),source:'manual'});closeModal();scheduleSave();render();return}
  if(a==='tempSwap'){const x=state.operations.temporarySchedules.find(y=>y.id===b.dataset.id);if(!x)return;const cid=$('#tmpSwapClass').value,[d1,p1]=$('#tmpSlotA').value.split('-').map(Number),[d2,p2]=$('#tmpSlotB').value.split('-').map(Number),w=Number(x.week||0);const at=(d,p)=>(x.placements||[]).filter(q=>q.week===w&&q.day===d&&q.period===p&&lessonById(state,q.lessonId)?.classIds?.includes(cid));const A=at(d1,p1),B=at(d2,p2);if(A.length!==1||B.length!==1)return toast('この入替は単一授業同士の場合に利用できます','warn');const la=lessonById(state,A[0].lessonId),lb=lessonById(state,B[0].lessonId);if(la.syncGroup||lb.syncGroup||la.classIds.length!==1||lb.classIds.length!==1)return toast('合同・同時展開授業はこの簡易入替の対象外です','warn');[A[0].day,A[0].period,B[0].day,B[0].period]=[d2,p2,d1,p1];x.changes.push({type:'swap',text:`${classById(state,cid)?.name||cid}：${DAYS[d1]}${p1+1}限と${DAYS[d2]}${p2+1}限を入替`});scheduleSave();showTemporaryDetail(x.id);return}
  if(a==='tempRemoveSlot'||a==='tempRemoveShift'){const x=state.operations.temporarySchedules.find(y=>y.id===b.dataset.id);if(!x)return;const [d,p]=$('#tmpRemoveSlot').value.split('-').map(Number),w=Number(x.week||0);x.placements=(x.placements||[]).filter(q=>!(q.week===w&&q.day===d&&q.period===p));if(a==='tempRemoveShift')for(const q of x.placements)if(q.week===w&&q.day===d&&q.period>p)q.period--;x.changes.push({type:'event',text:`${DAYS[d]}${p+1}限を休止${a==='tempRemoveShift'?'し、後続時限を前詰め':''}`});scheduleSave();showTemporaryDetail(x.id);return}
}catch(err){console.error(err);toast(err.message||String(err),'err')}}

function saveLessonFromModal(id,isNew){const classes=selectedValues('lessonClasses'),teachers=selectedValues('lessonTeachers'),subject=$('#lessonSubject').value.trim();if(!subject||!classes.length)return toast('授業名と対象学級を設定してください','warn');const data={id,subject,name:subject,classIds:classes,teacherIds:teachers,facilityId:$('#lessonFacility').value,annualHours:n($('#lessonHours').value),cycleSessionsOverride:$('#lessonCycle').value===''?null:n($('#lessonCycle').value),type:$('#lessonType').value,syncGroup:$('#lessonSync').value.trim(),allowTeacherTBD:$('#lessonTeacherTBD').checked,allowFacilityTBD:$('#lessonFacilityTBD').checked,unavailable:selectedValues('lessonUnavailable'),preferred:(lessonById(state,id)?.preferred||[])};if(!data.allowTeacherTBD&&!teachers.length)return toast('担当教員を設定するか「教員未定を許可」を選択してください','warn');if(isNew)state.lessons.push(data);else{const i=state.lessons.findIndex(x=>x.id===id);if(i>=0)state.lessons[i]=data}closeModal();scheduleSave();refreshMetrics();render()}

function importJsonDialog(){openModal('JSONバックアップを復元',`<div class="notice warn">現在の端末内データを置き換えます。必要なら先にバックアップしてください。</div><div class="field" style="margin-top:10px"><label>JSONファイル</label><input type="file" id="jsonFile" accept="application/json,.json"></div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="doImportJson">復元</button>`)}
async function importJsonFile(){const file=$('#jsonFile')?.files?.[0];if(!file)return toast('ファイルを選択してください','warn');const txt=await readFile(file),raw=JSON.parse(txt);state=migrateState(raw);await saveState(state);closeModal();metricsCache=null;absenceCache=null;render();refreshMetrics();toast('バックアップを復元しました','ok')}
function exportLessonCsv(){const head=['id','subject','classes','teachers','facility','annualHours','type','syncGroup'];const rows=state.lessons.map(l=>[l.id,l.subject,(l.classIds||[]).join('|'),(l.teacherIds||[]).join('|'),l.facilityId||'',l.annualHours,l.type,l.syncGroup||'']);downloadText(`lessons_${state.school.fiscalYear}.csv`,[head,...rows].map(r=>r.map(csvCell).join(',')).join('\n'),'text/csv;charset=utf-8')}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],nxt=text[i+1];if(q){if(c==='"'&&nxt==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}}row.push(cell);if(row.some(x=>x!==''))rows.push(row);return rows}
function importLessonCsvDialog(){openModal('授業設定CSVを読み込む',`<div class="notice info">CSV列：id, subject, classes（|区切りID）, teachers（|区切りID）, facility, annualHours, type, syncGroup。既存IDと同じ行は更新します。</div><div class="field" style="margin-top:10px"><input type="file" id="lessonCsvFile" accept=".csv,text/csv"></div>`,`<button class="btn" data-action="closeModal">キャンセル</button><button class="btn primary" data-action="doImportLessonCsv">読込</button>`)}
async function importLessonCsv(){const f=$('#lessonCsvFile')?.files?.[0];if(!f)return toast('CSVを選択してください','warn');const rows=parseCsv(await readFile(f));if(rows.length<2)return toast('データ行がありません','warn');const h=rows[0].map(x=>x.trim());for(const r of rows.slice(1)){const o=Object.fromEntries(h.map((k,i)=>[k,r[i]??'']));if(!o.subject)continue;const id=o.id||uid('l');const data={id,subject:o.subject,name:o.subject,classIds:o.classes?o.classes.split('|').filter(Boolean):[],teacherIds:o.teachers?o.teachers.split('|').filter(Boolean):[],facilityId:o.facility||'',annualHours:n(o.annualHours),cycleSessionsOverride:null,type:o.type||'normal',syncGroup:o.syncGroup||'',allowTeacherTBD:false,allowFacilityTBD:false};const i=state.lessons.findIndex(x=>x.id===id);if(i>=0)state.lessons[i]={...state.lessons[i],...data};else state.lessons.push(data)}closeModal();scheduleSave();refreshMetrics();render();toast('CSVを読み込みました','ok')}

async function doSaveDrive(){state.drive.clientId=$('#driveClientId')?.value.trim()||state.drive.clientId;state.drive.folderName=$('#driveFolder')?.value.trim()||'CurriculumPlanner';toast('Google認証を開始します');const r=await saveToDrive(state);state.drive={...state.drive,...r};scheduleSave();showDriveModal();toast('Driveへ保存しました','ok')}
async function doLoadDrive(){state.drive.clientId=$('#driveClientId')?.value.trim()||state.drive.clientId;state.drive.folderName=$('#driveFolder')?.value.trim()||'CurriculumPlanner';if(!confirm('Drive上のデータで現在の端末データを置き換えます。よろしいですか？'))return;const r=await loadFromDrive(state);state=migrateState(r.data);state.drive.clientId=$('#driveClientId')?.value.trim()||state.drive.clientId;state.drive.folderId=r.folderId;state.drive.fileId=r.fileId;state.drive.lastSyncAt=new Date().toISOString();await saveState(state);closeModal();metricsCache=null;render();refreshMetrics();toast('Driveから読み込みました','ok')}

function printCurrentReport(){const type=state.ui.reportType||'summary';let opts={};if(type==='timetable')opts={kind:state.timetable.view.kind,id:state.timetable.view.id};const html=reportByType(state,type,opts),w=window.open('','_blank');if(!w)return toast('ポップアップを許可してください','warn');w.document.write(`<!doctype html><html lang="ja"><head><meta charset="utf-8"><title>帳票</title><link rel="stylesheet" href="${new URL('./styles.css',location.href).href}"><style>body{background:#fff}.report-sheet{box-shadow:none}</style></head><body>${html}<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}

// Secondary actions are kept separate so modal controls can be handled without making the main router brittle.
const originalBindGlobal=bindGlobal;
// The main init calls bindGlobal once; attach the modal listener here after DOM availability.
queueMicrotask(()=>document.body.addEventListener('click',async e=>{
  const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;try{
    if(['saveCalendarException','saveEvent','saveIntegratedLinks','addTeacherLeave','deleteTeacherLeave','saveTeacherConstraints','saveFacilityConstraints','saveLesson','saveTemporary','tempSwap','tempRemoveSlot','tempRemoveShift'].includes(a)){await handleSecondaryClick(e);return}
    if(a==='doImportJson'){await importJsonFile();return}
    if(a==='doImportLessonCsv'){await importLessonCsv();return}
    if(a==='printReport'){e.stopImmediatePropagation();printCurrentReport();return}
  }catch(err){console.error(err);toast(err.message||String(err),'err')}
}));

init().catch(err=>{console.error(err);document.body.innerHTML=`<div style="padding:30px;font-family:sans-serif"><h1>起動エラー</h1><pre>${esc(err.stack||err.message||String(err))}</pre></div>`});
